import {setupRichEditors} from './rich-text.js';
import {db,esc,photo} from './database.js';
const $=s=>document.querySelector(s), form=$('#editor'), notice=$('#notice');let id=null,photos=[];
const richEditors=setupRichEditors(form);
const fields=[['title','Titel','text'],['year','Bouwjaar','number'],['mileage','Kilometerstand','number'],['price','Prijs in EUR','number'],['horsepower','Vermogen in PK','number'],['fuel','Brandstof','text'],['transmission','Transmissie','text'],['engine','Motor / cilinderinhoud','text'],['body','Carrosserie','text'],['color','Kleur','text']];
$('#fields').innerHTML=fields.map(([name,label,type])=>`<label>${label}<input name="${name}" type="${type}" ${name==='title'?'required':''} ${type==='number'?'min="0" step="1"':''}></label>`).join('');
function message(t){notice.textContent=t}
function renderPhotos(){ $('#photos').innerHTML=photos.map((p,i)=>`<div><img src="${esc(photo(p))}" alt="Foto ${i+1}"><div><button type="button" data-move="${i}" data-dir="-1">←</button><button type="button" data-move="${i}" data-dir="1">→</button><button type="button" data-remove="${i}">Weg</button></div></div>`).join('') }
$('#photos').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.remove!==undefined)photos.splice(Number(b.dataset.remove),1);else{const i=Number(b.dataset.move),j=i+Number(b.dataset.dir);if(j>=0&&j<photos.length)[photos[i],photos[j]]=[photos[j],photos[i]]}renderPhotos()};
function edit(c={}){id=c.id||null;form.reset();fields.forEach(([n])=>form.elements[n].value=c[n]??'');form.elements.description.value=c.description||'';form.elements.options.value=c.options||'';richEditors.load(c);form.elements.status.value=c.status||'Te koop';form.elements.published.checked=!!c.published;photos=[...(c.photos||[])];renderPhotos()}
async function list(){const {data,error}=await db.from('cars').select('*').order('created_at');if(error)throw error;$('#list').replaceChildren();data.forEach(c=>{const b=document.createElement('button');b.textContent=c.title+(c.published?' — online':' — concept');b.onclick=()=>edit(c);$('#list').append(b)})}
async function session(){const {data:{session}}=await db.auth.getSession();if(!session)return;const {data,error}=await db.from('admins').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!data){message('Dit account heeft nog geen beheerdersrechten. Volg de setup-instructies.');return}$('#login').hidden=true;$('#workspace').hidden=false;await list();edit()}
$('#login').onsubmit=async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#password').value='';if(error)message(error.message);else try{await session()}catch(e){message(e.message)}};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};$('#new').onclick=()=>edit();
$('#uploads').onchange=async e=>{const files=[...e.target.files];$('#save').disabled=true;try{for(const f of files){if(f.size>10485760)throw Error('Foto te groot: '+f.name);const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[f.type];if(!ext)throw Error('Gebruik JPG, PNG of WebP');const p=crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('car-photos').upload(p,f,{contentType:f.type,upsert:false});if(error)throw error;photos.push(p);renderPhotos()}message('Foto’s geüpload. Klik Opslaan om ze aan de auto te koppelen.')}catch(e){message(e.message)}finally{$('#save').disabled=false;e.target.value=''}};
form.onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;try{const values={};fields.forEach(([n,,t])=>values[n]=t==='number'?(form.elements[n].value===''?null:Number(form.elements[n].value)):form.elements[n].value.trim());Object.assign(values,{...richEditors.values(),status:form.elements.status.value,published:form.elements.published.checked,photos});if(values.published&&!photos.length)throw Error('Voeg minimaal één foto toe voor publicatie.');const query=id?db.from('cars').update(values).eq('id',id):db.from('cars').insert(values);const {data,error}=await query.select().single();if(error)throw error;id=data.id;await list();message('Opgeslagen'+(values.published?' — de auto staat nu op de website.':' als concept.'))}catch(e){message(e.message)}finally{$('#save').disabled=false}};
session().catch(e=>message(e.message));
